name: "Voltronic"
description: "Monitor and control Voltronic based inverters from Home Assistant."
version: "1.0.3"
slug: "voltronic"
init: false
udev: true

# Añadido
privileged: true
full_access: true
apparmor: false
# fin añadido

devices:
  - /dev/ttyS0
  - /dev/ttyUSB0
  - /dev/hidraw0
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

options:
  mqtt_broker_host: "homeassistant"
  mqtt_username: "mqtt_user"
  mqtt_password: "mqtt_password"
  device_name: "device_name"
  device_type: usb

schema:
  mqtt_broker_host: str
  mqtt_username: str
  mqtt_password: str
  device_name: str
  device_type: list(serial|usb-serial|usb)
